/**
 * The parity test. This is the mechanism that makes duplicating the check logic safe.
 *
 * The edge cannot run the Python library, so `src/report.ts` reimplements the rules. Two
 * implementations of one rule set is two sets of bugs — unless something fails loudly the
 * moment they disagree. That is this file.
 *
 * The fixture is generated by the real Python tool:
 *
 *     grantcheck --ein 27-1067272 --format json > test/fixtures/report-27-1067272.json
 *
 * Regenerate it when the library's output legitimately changes, and the diff in review then
 * shows both sides moving together.
 *
 * When this first ran it found seven differences — two missing lookup tables and four
 * abbreviated sentences — every one a place where a reader comparing the site to the CLI
 * would have got a different answer to the same question.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import type { OrgRow, Report, Vintage } from "../src/report";
import { buildReport } from "../src/report";

const FIXTURE_DIR = join(import.meta.dirname, "fixtures");

const expected: Report = JSON.parse(
  readFileSync(join(FIXTURE_DIR, "report-27-1067272.json"), "utf8"),
);
const row: OrgRow = JSON.parse(readFileSync(join(FIXTURE_DIR, "row-27-1067272.json"), "utf8"));
const vintages: Record<string, Vintage> = JSON.parse(
  readFileSync(join(FIXTURE_DIR, "vintages.json"), "utf8"),
);

/**
 * Two fields legitimately differ and are excluded, with the reason stated:
 *
 * - `queried_at` is the moment of the request, by definition different every time.
 * - a cache-staleness note is a property of the caller's machine. The CLI adds one when it
 *   served from a stale local cache; the edge has no local cache to be stale.
 */
function comparable(report: Report): Omit<Report, "queried_at"> {
  const { queried_at: _ignored, ...rest } = report;
  return {
    ...rest,
    notes: rest.notes.filter((n) => !n.includes("could not be refreshed")),
  };
}

describe("the site and the command-line tool produce the same report", () => {
  const actual = buildReport(row, "271067272", vintages, new Date("2026-09-01T12:00:00Z"));

  it("produces an identical payload", () => {
    expect(comparable(actual)).toEqual(comparable(expected));
  });

  it("agrees on the verdict", () => {
    expect(actual.readiness).toBe(expected.readiness);
    expect(actual.blocking_check_ids).toEqual(expected.blocking_check_ids);
  });

  it("agrees on every check id, in order", () => {
    expect(actual.checks.map((c) => c.id)).toEqual(expected.checks.map((c) => c.id));
  });

  it("agrees on every status", () => {
    for (const [i, check] of actual.checks.entries()) {
      expect(check.status, `check ${check.id}`).toBe(expected.checks[i]?.status);
    }
  });

  it("agrees on the prose, which is where drift actually happened", () => {
    for (const [i, check] of actual.checks.entries()) {
      expect(check.value, `${check.id}.value`).toBe(expected.checks[i]?.value ?? null);
      expect(check.detail, `${check.id}.detail`).toBe(expected.checks[i]?.detail ?? null);
    }
  });

  it("carries the same schema version and disclosure", () => {
    expect(actual.schema_version).toBe(expected.schema_version);
    expect(actual.disclosure).toBe(expected.disclosure);
  });

  it("attributes the same vintages", () => {
    expect(actual.vintages).toEqual(expected.vintages);
  });
});

describe("the rules that must never regress", () => {
  const base: OrgRow = { ...row };

  it("an unknown never produces blocked", () => {
    // An unchecked thing is not a failed thing. Conflating them tells a compliant
    // organization it cannot apply for federal money.
    const report = buildReport(
      { ...base, in_bmf: 0, in_pub78: 0, in_revocation: 0, in_epostcard: 0 },
      "271067272",
      vintages,
      new Date("2026-09-01T12:00:00Z"),
    );
    expect(report.readiness).not.toBe("blocked");
  });

  it("a group subordinate absent from Publication 78 is not applicable, never a failure", () => {
    const report = buildReport(
      { ...base, in_pub78: 0, group_exemption: "3514", affiliation: "9" },
      "271067272",
      vintages,
      new Date("2026-09-01T12:00:00Z"),
    );
    const check = report.checks.find((c) => c.id === "pub78_deductibility");
    expect(check?.status).toBe("not_applicable");
  });

  it("a central organization is not excused by the group rule", () => {
    // Affiliation 6 carries the group number too and IS listed. Keying on GROUP alone would
    // wrongly excuse ~2,560 central organizations.
    const report = buildReport(
      { ...base, in_pub78: 0, group_exemption: "3514", affiliation: "6" },
      "271067272",
      vintages,
      new Date("2026-09-01T12:00:00Z"),
    );
    expect(report.checks.find((c) => c.id === "pub78_deductibility")?.status).toBe("warn");
  });

  it("a reinstated organization passes", () => {
    const report = buildReport(
      {
        ...base,
        in_revocation: 1,
        revocation_date: "2013-06-15",
        reinstatement_date: "2013-06-15",
      },
      "271067272",
      vintages,
      new Date("2026-09-01T12:00:00Z"),
    );
    expect(report.checks.find((c) => c.id === "auto_revocation")?.status).toBe("pass");
  });

  it("a revoked organization with an older reinstatement is still blocked", () => {
    const report = buildReport(
      {
        ...base,
        in_revocation: 1,
        revocation_date: "2017-06-15",
        reinstatement_date: "2013-06-15",
      },
      "271067272",
      vintages,
      new Date("2026-09-01T12:00:00Z"),
    );
    expect(report.readiness).toBe("blocked");
  });

  it("a church is never flagged delinquent", () => {
    const report = buildReport(
      { ...base, filing_req_cd: "06", pf_filing_req_cd: "0", in_epostcard: 0, tax_period: null },
      "271067272",
      vintages,
      new Date("2026-09-01T12:00:00Z"),
    );
    expect(report.checks.find((c) => c.id === "filing_recency")?.status).toBe("not_applicable");
  });

  it("a private foundation is not treated as exempt from filing", () => {
    // FILING_REQ_CD=00 alone reads as "no return required"; PF_FILING_REQ_CD=1 says
    // otherwise, for 129,561 organizations.
    const report = buildReport(
      { ...base, filing_req_cd: "00", pf_filing_req_cd: "1", tax_period: "2024-12" },
      "271067272",
      vintages,
      new Date("2026-09-01T12:00:00Z"),
    );
    expect(report.checks.find((c) => c.id === "filing_recency")?.value).not.toBe(
      "No annual return required",
    );
  });

  it("the single audit screen never fails", () => {
    const report = buildReport(base, "271067272", vintages, new Date("2026-09-01T12:00:00Z"));
    const check = report.checks.find((c) => c.id === "single_audit");
    expect(check?.status).not.toBe("fail");
    expect(check?.blocking).toBe(false);
  });
});
