/**
 * The report shape, and the checks that produce it.
 *
 * This is a deliberate second implementation of the check logic, in TypeScript, because the
 * edge cannot run the Python library. That duplication is a real risk — two implementations
 * of one set of rules is two sets of bugs — so it is managed rather than ignored:
 *
 * - The JSON output is asserted byte-for-byte against a fixture generated by the Python
 *   tool, in CI. If the two ever disagree, the build fails.
 * - Every rule below carries the same comment as its Python counterpart, so a change to one
 *   is visibly a change to the other.
 * - The D1 rows are produced by the same ingest that produces the Python index, so the two
 *   can never disagree about the underlying data — only about the interpretation, which is
 *   what the parity test covers.
 */

export type Status = "pass" | "warn" | "fail" | "unknown" | "not_applicable";
export type Readiness = "ready" | "attention" | "blocked" | "not_found";

export type Vintage = { dataset: string; published: string; source_url: string };

export type Check = {
  id: string;
  label: string;
  group: string;
  status: Status;
  blocking: boolean;
  value: string | null;
  detail: string | null;
  vintage: Vintage | null;
  confidence: number | null;
};

export type Organization = {
  ein: string;
  name: string;
  sort_name: string | null;
  city: string | null;
  state: string | null;
  ntee_code: string | null;
  subsection: string | null;
  classification: string | null;
  foundation_code: string | null;
  group_exemption: string | null;
  ruling_date: string | null;
  uei: string | null;
};

export type Report = {
  schema_version: string;
  ein: string;
  queried_at: string;
  organization: Organization | null;
  checks: Check[];
  readiness: Readiness;
  blocking_check_ids: string[];
  opportunities: null;
  vintages: Vintage[];
  disclosure: string;
  notes: string[];
};

export const SCHEMA_VERSION = "1.0";

export const DISCLOSURE =
  "This is informational only, derived from public data on the dates shown. It is not an " +
  "eligibility determination, and not legal, tax, or accounting advice. Verify against the " +
  "official source before relying on it.";

/**
 * Label for a readiness value that came back from the database as a plain string.
 *
 * Round-tripping through D1 loses the union type, and every caller casting it back is a
 * cast that will eventually be wrong. This narrows in one place and falls back to the raw
 * value rather than rendering "undefined".
 */
export function verdictLabel(readiness: string): string {
  return (VERDICT_LABEL as Record<string, string>)[readiness] ?? readiness;
}

export const VERDICT_LABEL: Record<Readiness, string> = {
  ready: "Ready to apply",
  attention: "Needs attention",
  blocked: "Not ready",
  not_found: "Not found",
};

export const DATASET_NAMES: Record<string, string> = {
  bmf: "the IRS EO Business Master File",
  pub78: "IRS Publication 78",
  revocation: "the IRS Automatic Revocation List",
  epostcard: "the IRS Form 990-N e-Postcard file",
  efile_index: "the IRS Form 990 e-file index",
  sam: "SAM.gov Entity Management",
  fac: "the Federal Audit Clearinghouse",
};

/**
 * Nine digits after normalization, or it never touches the database.
 *
 * Mirrors `grantcheck.ein.normalize`, including the narrowness of the rejection: all zeros
 * is a placeholder, but the 00 *prefix* is real and issued. The IRS files carry 136
 * organizations with it, 90 of them on the automatic revocation list — the answers this
 * site most needs to give.
 */
export function normalizeEin(raw: string): string | null {
  const digits = raw.replace(/[\s–—-]/g, "");
  if (!/^[0-9]{9}$/.test(digits)) return null;
  if (/^0{9}$/.test(digits)) return null; // a placeholder, not an EIN
  return digits;
}

/** One denormalized row from D1, matching the Python index schema exactly. */
export type OrgRow = {
  ein: string;
  in_bmf: number;
  in_pub78: number;
  in_revocation: number;
  in_epostcard: number;
  name: string | null;
  sort_name: string | null;
  city: string | null;
  state: string | null;
  group_exemption: string | null;
  affiliation: string | null;
  subsection: string | null;
  classification: string | null;
  ruling: string | null;
  foundation: string | null;
  exempt_status: string | null;
  tax_period: string | null;
  filing_req_cd: string | null;
  pf_filing_req_cd: string | null;
  acct_pd: string | null;
  ntee_cd: string | null;
  pub78_deductibility_code: string | null;
  revocation_date: string | null;
  revocation_posting_date: string | null;
  reinstatement_date: string | null;
  epostcard_tax_year: string | null;
  epostcard_period_end: string | null;
  uei: string | null;
  sam_status: string | null;
  sam_expiration: string | null;
  sam_purpose: string | null;
  sam_match_confidence: number | null;
};

// AFFILIATION 7 and 9 mean covered by ANOTHER organization's group ruling. Measured across
// every subsection-03 row: 9 and 7 are 0.0% listed in Publication 78, while 6 (central) and
// 8 are ~99.5% listed. Keying on GROUP alone would wrongly excuse ~2,560 central orgs.
const COVERED_BY_ANOTHERS_RULING = new Set(["7", "9"]);

// 433,337 subsection-03 organizations carry one of these and are not required to file at
// all. Churches alone are 287,356. Flagging any of them delinquent is a false accusation.
const NO_FILING_REQUIREMENT: Record<string, string> = {
  "00": "not required to file",
  "06": "a church, not required to file",
  "07": "a government 501(c)(1) organization",
  "13": "a religious organization not required to file",
  "14": "an instrumentality of a state or political subdivision",
};

// Sourced from the published EO BMF data dictionary, mirroring checks/organization_type.py.
// Without this the site said "Public charity, not a private foundation" where the library
// said "Public charity — publicly supported organization".
const PUBLIC_CHARITY_CODES: Record<string, string> = {
  "09": "suborganization of a public charity",
  "10": "church",
  "11": "school",
  "12": "hospital or medical research organization",
  "13": "organization supported by a governmental unit",
  "14": "publicly supported organization",
  "15": "publicly supported organization",
  "16": "supporting organization, section 509(a)(3)",
  "17": "public safety testing organization",
  "18": "supporting organization, section 509(a)(3)",
  "21": "509(a)(3) supporting organization, type unspecified",
};

const PRIVATE_FOUNDATION_CODES: Record<string, string> = {
  "02": "private operating foundation, exempt operating foundation",
  "03": "private operating foundation (other)",
  "04": "private non-operating foundation",
};

// The NTEE major group letter. Mirrors checks/ntee.py.
const NTEE_MAJOR_GROUPS: Record<string, string> = {
  A: "Arts, Culture and Humanities",
  B: "Education",
  C: "Environment",
  D: "Animal-Related",
  E: "Health Care",
  F: "Mental Health and Crisis Intervention",
  G: "Voluntary Health Associations and Medical Disciplines",
  H: "Medical Research",
  I: "Crime and Legal-Related",
  J: "Employment",
  K: "Food, Agriculture and Nutrition",
  L: "Housing and Shelter",
  M: "Public Safety, Disaster Preparedness and Relief",
  N: "Recreation and Sports",
  O: "Youth Development",
  P: "Human Services",
  Q: "International, Foreign Affairs and National Security",
  R: "Civil Rights, Social Action and Advocacy",
  S: "Community Improvement and Capacity Building",
  T: "Philanthropy, Voluntarism and Grantmaking Foundations",
  U: "Science and Technology",
  V: "Social Science",
  W: "Public and Societal Benefit",
  X: "Religion-Related",
  Y: "Mutual and Membership Benefit",
  Z: "Unknown",
};

const PUB78_MEANINGS: Record<string, string> = {
  PC: "public charity",
  PF: "private foundation",
  POF: "private operating foundation",
  SO: "supporting organization",
  SOUNK: "supporting organization, type unspecified",
  EO: "an organization other than a charity",
  GROUP: "a group ruling",
  FORGN: "a foreign organization",
  UNKWN: "type not stated",
};

function isGroupSubordinate(row: OrgRow): boolean {
  const group = (row.group_exemption ?? "").trim();
  if (!group || /^0+$/.test(group)) return false;
  return COVERED_BY_ANOTHERS_RULING.has((row.affiliation ?? "").trim());
}

function files990pf(row: OrgRow): boolean {
  const code = (row.pf_filing_req_cd ?? "").trim();
  return code !== "" && code !== "0";
}

function exemptFromFiling(row: OrgRow): string | null {
  // Private foundations carry FILING_REQ_CD=00, which alone reads as "no return required",
  // and 129,561 of them also carry PF_FILING_REQ_CD=1: they file a 990-PF and face the same
  // three-year revocation counter. Reading only the first code tells all of them they have
  // no filing obligation.
  if (files990pf(row)) return null;
  const code = (row.filing_req_cd ?? "").trim();
  if (code in NO_FILING_REQUIREMENT) return NO_FILING_REQUIREMENT[code] ?? null;
  if (code === "03") return "covered by a group return";
  return null;
}

function yearsSince(isoDate: string, today: Date): number {
  const then = new Date(`${isoDate}T00:00:00Z`);
  let years = today.getUTCFullYear() - then.getUTCFullYear();
  const monthDay = (d: Date) => d.getUTCMonth() * 100 + d.getUTCDate();
  if (monthDay(today) < monthDay(then)) years -= 1;
  return Math.max(0, years);
}

function monthEnd(yyyymm: string): string | null {
  const parts = yyyymm.split("-");
  const year = Number(parts[0]);
  const month = Number(parts[1]);
  if (!Number.isInteger(year) || !Number.isInteger(month) || month < 1 || month > 12) return null;
  const last = new Date(Date.UTC(year, month, 0));
  return last.toISOString().slice(0, 10);
}

export function deriveReadiness(checks: Check[], found: boolean): Readiness {
  if (!found) return "not_found";
  // An `unknown` never produces `blocked`. An unchecked thing is not a failed thing, and
  // conflating them tells a compliant organization it cannot apply for federal money.
  if (checks.some((c) => c.status === "fail" && c.blocking)) return "blocked";
  if (checks.some((c) => c.status === "warn" || (c.status === "fail" && !c.blocking)))
    return "attention";
  return "ready";
}

export function formatEin(nine: string): string {
  return `${nine.slice(0, 2)}-${nine.slice(2)}`;
}

export function buildReport(
  row: OrgRow | null,
  ein: string,
  vintages: Record<string, Vintage>,
  now: Date,
): Report {
  const formatted = formatEin(ein);
  const base = {
    schema_version: SCHEMA_VERSION,
    ein: formatted,
    queried_at: now.toISOString().replace(".000Z", "+00:00"),
    opportunities: null as null,
    disclosure: DISCLOSURE,
    notes: [] as string[],
  };

  if (!row) {
    return {
      ...base,
      organization: null,
      checks: [],
      readiness: "not_found",
      blocking_check_ids: [],
      vintages: Object.values(vintages).sort((a, b) => a.dataset.localeCompare(b.dataset)),
    };
  }

  const v = (name: string): Vintage | null => vintages[name] ?? null;
  const checks: Check[] = [];
  const add = (c: Check) => checks.push(c);

  // --- exempt_status --------------------------------------------------------------------
  {
    const subsection = (row.subsection ?? "").trim();
    const status = (row.exempt_status ?? "").trim();
    if (!row.in_bmf) {
      add({
        id: "exempt_status",
        label: "Exempt status",
        group: "tax_exemption",
        status: "unknown",
        blocking: true,
        value: null,
        detail:
          "This EIN is not in the IRS Exempt Organizations Business Master File. Churches, " +
          "their integrated auxiliaries, and government instrumentalities are exempt without " +
          "applying and are frequently absent. Absence here is not evidence of a problem.",
        vintage: v("bmf"),
        confidence: null,
      });
    } else if (subsection === "03" && status === "01") {
      add({
        id: "exempt_status",
        label: "Exempt status",
        group: "tax_exemption",
        status: "pass",
        blocking: true,
        value: "501(c)(3), unconditional exemption",
        detail: row.ruling
          ? `Recognized under section 501(c)(3), ruling dated ${row.ruling}.`
          : "Recognized under section 501(c)(3).",
        vintage: v("bmf"),
        confidence: null,
      });
    } else if (subsection !== "03") {
      add({
        id: "exempt_status",
        label: "Exempt status",
        group: "tax_exemption",
        status: "fail",
        blocking: true,
        value: /^\d+$/.test(subsection) ? `501(c)(${Number(subsection)})` : "Not 501(c)(3)",
        detail: `The Business Master File records this organization under subsection ${subsection}, not 03. Most federal grant programs limit eligibility to organizations described in section 501(c)(3).`,
        vintage: v("bmf"),
        confidence: null,
      });
    } else {
      add({
        id: "exempt_status",
        label: "Exempt status",
        group: "tax_exemption",
        status: "warn",
        blocking: false,
        value: `501(c)(3), status code ${status}`,
        detail: `Recognized under section 501(c)(3), but the exemption status code is ${status} rather than 01 (unconditional exemption). Worth confirming with the IRS.`,
        vintage: v("bmf"),
        confidence: null,
      });
    }
  }

  // --- pub78_deductibility --------------------------------------------------------------
  {
    const code = (row.pub78_deductibility_code ?? "").trim();
    if (row.in_pub78) {
      const meaning = PUB78_MEANINGS[code];
      add({
        id: "pub78_deductibility",
        label: "Pub 78 deductibility",
        group: "tax_exemption",
        status: "pass",
        blocking: false,
        value: meaning ? `Listed — ${code} (${meaning})` : `Listed — ${code}`,
        detail:
          "Listed in IRS Publication 78, the roster of organizations eligible to receive " +
          "tax-deductible charitable contributions.",
        vintage: v("pub78"),
        confidence: null,
      });
    } else if (isGroupSubordinate(row)) {
      // The trap: a subordinate is absent from Publication 78 by design. The central
      // organization is listed and the ruling covers it. ~238,000 organizations.
      add({
        id: "pub78_deductibility",
        label: "Pub 78 deductibility",
        group: "tax_exemption",
        status: "not_applicable",
        blocking: false,
        value: "Covered by a group ruling",
        detail: `This organization is a subordinate under group exemption number ${row.group_exemption}, so it does not appear in Publication 78 in its own right — the central organization is listed and the ruling covers its subordinates. This is normal and is not a problem.`,
        vintage: v("pub78"),
        confidence: null,
      });
    } else if (!row.in_bmf) {
      add({
        id: "pub78_deductibility",
        label: "Pub 78 deductibility",
        group: "tax_exemption",
        status: "unknown",
        blocking: false,
        value: null,
        detail:
          "Not listed in Publication 78, and not in the Business Master File either, so there " +
          "is nothing to interpret the absence against.",
        vintage: v("pub78"),
        confidence: null,
      });
    } else {
      add({
        id: "pub78_deductibility",
        label: "Pub 78 deductibility",
        group: "tax_exemption",
        status: "warn",
        blocking: false,
        value: "Not listed",
        detail:
          "Not listed in IRS Publication 78. Common reasons are a recent recognition that has " +
          "not propagated, a revoked exemption, or a church that is eligible without being " +
          "listed. It is not by itself a disqualification.",
        vintage: v("pub78"),
        confidence: null,
      });
    }
  }

  // --- auto_revocation ------------------------------------------------------------------
  {
    const revoked = row.revocation_date;
    const reinstated = row.reinstatement_date;
    if (!row.in_revocation) {
      add({
        id: "auto_revocation",
        label: "Auto-revocation",
        group: "tax_exemption",
        status: "pass",
        blocking: true,
        value: "No revocation on record",
        detail: "This EIN does not appear on the IRS Automatic Revocation of Exemption List.",
        vintage: v("revocation"),
        confidence: null,
      });
    } else if (revoked && reinstated && reinstated >= revoked) {
      // Reinstatement is frequently retroactive to the revocation date, so the test is
      // "on or after". 181,259 of 1,246,171 rows carry a reinstatement date.
      add({
        id: "auto_revocation",
        label: "Auto-revocation",
        group: "tax_exemption",
        status: "pass",
        blocking: true,
        value: `Revoked ${revoked}, reinstated ${reinstated}`,
        detail: `The exemption was automatically revoked on ${revoked} and reinstated on ${reinstated}. Organizations stay on the published list permanently once revoked, so presence there is history rather than current status. It is in good standing on this measure.`,
        vintage: v("revocation"),
        confidence: null,
      });
    } else if (revoked) {
      add({
        id: "auto_revocation",
        label: "Auto-revocation",
        group: "tax_exemption",
        status: "fail",
        blocking: true,
        value: `Revoked ${revoked}`,
        detail: `The exemption was automatically revoked on ${revoked} for three consecutive years of non-filing, and no later reinstatement is recorded. Revoked organizations are ineligible for federal grants and cannot receive tax-deductible contributions until reinstated. Reinstatement is by Form 1023 or 1023-EZ; see IRS Rev. Proc. 2014-11.`,
        vintage: v("revocation"),
        confidence: null,
      });
    } else {
      add({
        id: "auto_revocation",
        label: "Auto-revocation",
        group: "tax_exemption",
        status: "unknown",
        blocking: true,
        value: "On the list, dates unreadable",
        detail:
          "This EIN appears on the Automatic Revocation List but its revocation date could not " +
          "be read. Check the IRS Tax Exempt Organization Search directly.",
        vintage: v("revocation"),
        confidence: null,
      });
    }
  }

  // --- organization_type ----------------------------------------------------------------
  {
    const code = (row.foundation ?? "").trim();
    if (!row.in_bmf || !code) {
      add({
        id: "organization_type",
        label: "Organization type",
        group: "tax_exemption",
        status: "unknown",
        blocking: false,
        value: null,
        detail:
          "The Business Master File does not record a foundation classification for this EIN.",
        vintage: v("bmf"),
        confidence: null,
      });
    } else if (code in PRIVATE_FOUNDATION_CODES) {
      add({
        id: "organization_type",
        label: "Organization type",
        group: "tax_exemption",
        status: "warn",
        blocking: false,
        value: `Private foundation (${PRIVATE_FOUNDATION_CODES[code]})`,
        detail:
          "Classified as a private foundation. Most federal grant programs restrict eligibility " +
          "to public charities and exclude private foundations. It is a classification, not a " +
          "disqualification — check the specific notice of funding opportunity.",
        vintage: v("bmf"),
        confidence: null,
      });
    } else {
      add({
        id: "organization_type",
        label: "Organization type",
        group: "tax_exemption",
        status: "pass",
        blocking: false,
        value: PUBLIC_CHARITY_CODES[code]
          ? `Public charity — ${PUBLIC_CHARITY_CODES[code]}`
          : "Public charity, not a private foundation",
        detail:
          "Not classified as a private foundation, so the exclusion most federal programs apply " +
          "to private foundations does not bite here.",
        vintage: v("bmf"),
        confidence: null,
      });
    }
  }

  // --- most_recent_filing and filing_recency --------------------------------------------
  {
    const exemption = exemptFromFiling(row);
    const epostcardEnd = row.in_epostcard ? row.epostcard_period_end : null;
    const fallbackEnd = row.tax_period ? monthEnd(row.tax_period) : null;

    if (epostcardEnd) {
      add({
        id: "most_recent_filing",
        label: "Most recent Form 990",
        group: "filing_health",
        status: "pass",
        blocking: false,
        value: `Tax period ending ${epostcardEnd}`,
        detail: `Most recent annual return on record is a Form 990-N (e-Postcard) for tax year ${row.epostcard_tax_year}. The 990-N is what most small organizations file, and it does not appear in the Form 990 e-file index.`,
        vintage: v("epostcard"),
        confidence: null,
      });
    } else if (fallbackEnd) {
      add({
        id: "most_recent_filing",
        label: "Most recent Form 990",
        group: "filing_health",
        status: "pass",
        blocking: false,
        value: `Tax period ending ${row.tax_period}`,
        detail:
          "This is the period of the most recent return the IRS has processed, at month " +
          "precision, taken from the Business Master File. It is not a filing date: processing " +
          "lags filing by weeks to more than a year, so the actual return may be considerably " +
          "more recent.",
        vintage: v("bmf"),
        confidence: null,
      });
    } else if (exemption) {
      add({
        id: "most_recent_filing",
        label: "Most recent Form 990",
        group: "filing_health",
        status: "not_applicable",
        blocking: false,
        value: "No annual return required",
        detail: `No return is on record, and none is required: the Business Master File records this organization as ${exemption}. An absent filing history is expected and is not a problem.`,
        vintage: v("bmf"),
        confidence: null,
      });
    } else {
      add({
        id: "most_recent_filing",
        label: "Most recent Form 990",
        group: "filing_health",
        status: "unknown",
        blocking: false,
        value: null,
        detail:
          "No annual return is recorded in the datasets this site publishes. That is not the " +
          "same as never having filed.",
        vintage: v("bmf"),
        confidence: null,
      });
    }

    const cliff =
      "Automatic revocation triggers after three consecutive years without filing a Form 990, " +
      "990-EZ, or 990-N.";
    if (exemption) {
      add({
        id: "filing_recency",
        label: "Years since filing",
        group: "filing_health",
        status: "not_applicable",
        blocking: false,
        value: "No annual return required",
        detail: `The Business Master File records this organization as ${exemption}, so the three-year automatic revocation counter does not apply.`,
        vintage: v("bmf"),
        confidence: null,
      });
    } else if (isGroupSubordinate(row)) {
      add({
        id: "filing_recency",
        label: "Years since filing",
        group: "filing_health",
        status: "not_applicable",
        blocking: false,
        value: "Covered by a group return",
        detail: `This organization is a subordinate under group exemption number ${row.group_exemption}. Subordinates are commonly included in the central organization's group return and have no filings of their own.`,
        vintage: v("bmf"),
        confidence: null,
      });
    } else if (epostcardEnd) {
      const years = yearsSince(epostcardEnd, now);
      const status: Status = years >= 3 ? "fail" : years === 2 ? "warn" : "pass";
      add({
        id: "filing_recency",
        label: "Years since filing",
        group: "filing_health",
        status,
        blocking: false,
        value: String(years),
        detail: `${years} year(s) since the most recent filing on record. ${cliff}`,
        vintage: v("epostcard"),
        confidence: null,
      });
    } else if (fallbackEnd) {
      // The fallback can never produce a failure: TAX_PERIOD lags real filing by up to a
      // year, so a count from it can be a year or more too high.
      const years = yearsSince(fallbackEnd, now);
      add({
        id: "filing_recency",
        label: "Years since filing",
        group: "filing_health",
        status: years >= 2 ? "warn" : "pass",
        blocking: false,
        value: `${years} (from the most recent processed return)`,
        detail: `Roughly ${years} year(s) since the end of the most recent tax period the IRS has processed. This comes from the Business Master File, which records a processing period rather than a filing date and can lag actual filing by more than a year, so treat it as approximate. ${cliff} Confirm against the IRS Tax Exempt Organization Search before acting on it.`,
        vintage: v("bmf"),
        confidence: null,
      });
    } else {
      add({
        id: "filing_recency",
        label: "Years since filing",
        group: "filing_health",
        status: "unknown",
        blocking: false,
        value: null,
        detail: `No filing period is on record, so the distance to automatic revocation cannot be computed. ${cliff}`,
        vintage: v("bmf"),
        confidence: null,
      });
    }
  }

  // --- ntee -----------------------------------------------------------------------------
  {
    const code = (row.ntee_cd ?? "").trim();
    add({
      id: "ntee",
      label: "NTEE classification",
      group: "filing_health",
      status: code ? "pass" : "unknown",
      blocking: false,
      value: code
        ? NTEE_MAJOR_GROUPS[code[0] ?? ""]
          ? `${code} — ${NTEE_MAJOR_GROUPS[code[0] ?? ""]}`
          : code
        : null,
      detail: code
        ? `The IRS records this organization under NTEE code ${code}. NTEE codes are self-reported at application and are frequently out of date, so it is worth confirming it still describes the work.`
        : "The Business Master File does not record an NTEE code for this organization. This is common and is not a problem in itself.",
      vintage: v("bmf"),
      confidence: null,
    });
  }

  // --- SAM.gov: three checks, one shared "not checked" when there is no snapshot ---------
  {
    const hasSam = Boolean(vintages.sam);
    const notChecked = (id: string, label: string): Check => ({
      id,
      label,
      group: "federal_registration",
      status: "unknown",
      blocking: true,
      value: "Not checked",
      detail:
        "This index build does not include SAM.gov data, so registration status, expiration, " +
        "and Unique Entity ID were not checked. Nothing here says anything about the " +
        "organization's registration — check it directly at https://sam.gov.",
      vintage: null,
      confidence: null,
    });

    if (!hasSam) {
      add(notChecked("sam_registration", "SAM.gov registration"));
      add(notChecked("sam_expiration", "Registration expires"));
      add(notChecked("uei", "Unique Entity ID"));
    } else {
      const status = (row.sam_status ?? "").trim();
      add({
        id: "sam_registration",
        label: "SAM.gov registration",
        group: "federal_registration",
        status: status.toUpperCase() === "ACTIVE" ? "pass" : status ? "fail" : "fail",
        blocking: true,
        value: status || "No registration found",
        detail: status
          ? "The SAM.gov entity registration status shown is as of the snapshot date."
          : "No SAM.gov entity registration was found. An active registration is required " +
            "before a federal grant application can be submitted.",
        vintage: v("sam"),
        confidence: row.sam_match_confidence,
      });
      add({
        id: "sam_expiration",
        label: "Registration expires",
        group: "federal_registration",
        status: row.sam_expiration ? "pass" : "unknown",
        blocking: true,
        value: row.sam_expiration,
        detail: "Registration lapses annually and renewal is not automatic.",
        vintage: v("sam"),
        confidence: null,
      });
      add({
        id: "uei",
        label: "Unique Entity ID",
        group: "federal_registration",
        status: row.uei ? "pass" : "fail",
        blocking: true,
        value: row.uei,
        detail: row.uei
          ? "A Unique Entity ID is on record."
          : "No Unique Entity ID is on record. One is required before any federal grant " +
            "application can be submitted.",
        vintage: v("sam"),
        confidence: null,
      });
    }
  }

  // --- single_audit ---------------------------------------------------------------------
  {
    const acct = (row.acct_pd ?? "").trim();
    const endMonth = Number(acct);
    let value: string | null = "Cannot be screened";
    let detail =
      "Whether a single audit is required depends on federal awards expended during the fiscal " +
      "year, which is not in this dataset. The threshold is $1,000,000 for fiscal years " +
      "beginning on or after 2024-10-01, and $750,000 for years beginning before it.";

    if (Number.isInteger(endMonth) && endMonth >= 1 && endMonth <= 12) {
      const beginMonth = endMonth === 12 ? 1 : endMonth + 1;
      let year = now.getUTCFullYear();
      let begin = new Date(Date.UTC(year, beginMonth - 1, 1));
      if (begin > now) {
        year -= 1;
        begin = new Date(Date.UTC(year, beginMonth - 1, 1));
      }
      const beginIso = begin.toISOString().slice(0, 10);
      // Keys on when the fiscal year BEGAN, not when it ended and not when you filed.
      const threshold = beginIso >= "2024-10-01" ? "$1,000,000" : "$750,000";
      value = `Threshold ${threshold} for the year beginning ${beginIso}`;
      const change =
        threshold === "$1,000,000"
          ? "It rose from $750,000 for years beginning before 2024-10-01."
          : "It rises to $1,000,000 for years beginning on or after 2024-10-01, so next " +
            "year's number is probably different.";
      detail = `Your current fiscal year began ${beginIso}, so the threshold that applies to it is ${threshold} in federal awards expended. ${change} This tool cannot tell you how much you expended — that figure is not in the public datasets it publishes. Count everything federal, including subawards passed through a state agency, a university, or a larger nonprofit, and count what was spent rather than what was received. Your Schedule of Expenditures of Federal Awards is where that number lives.`;
    }

    add({
      id: "single_audit",
      label: "Single audit",
      group: "audit_posture",
      // Never a failure. This is a screen against an incomplete figure.
      status: "unknown",
      blocking: false,
      value,
      detail,
      vintage: v("bmf"),
      confidence: null,
    });
  }

  const readiness = deriveReadiness(checks, true);
  const used = new Map<string, Vintage>();
  for (const c of checks) if (c.vintage) used.set(c.vintage.dataset, c.vintage);

  return {
    ...base,
    organization: {
      ein: formatted,
      name: row.name ?? "",
      sort_name: row.sort_name || null,
      city: row.city || null,
      state: row.state || null,
      ntee_code: row.ntee_cd || null,
      subsection: row.subsection || null,
      classification: row.classification || null,
      foundation_code: row.foundation || null,
      group_exemption: row.group_exemption || null,
      ruling_date: row.ruling || null,
      uei: row.uei || null,
    },
    checks,
    readiness,
    blocking_check_ids: checks.filter((c) => c.status === "fail" && c.blocking).map((c) => c.id),
    vintages: [...used.values()].sort((a, b) => a.dataset.localeCompare(b.dataset)),
  };
}
